apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-store
  annotations:
    # use the shared ingress-nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: store.local
    http:
      paths:
      - path: /v1/customers
        pathType: Prefix
        backend:
          service:
            name: customers-service
            port:
              number: 8080
      - path: /v1/products
        pathType: Prefix
        backend:
          service:
            name: products-service
            port:
              number: 8081